// import { photos } from './'

export interface ImageData {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  room: string;
  styles: string[];
  designer?: string;
  featured: boolean;
}

export const images: ImageData[] = [
  {
    id: '1',
    title: 'מטבח מודרני',
    description: 'מטבח עם קווים נקיים ועיצוב מינימליסטי.',
    imageUrl: photos.img1,
    room: 'מטבח',
    styles: ['מודרני', 'מינימליסטי'],
    designer: 'דנה לוי',
    featured: true,
  },
  {
    id: '2',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img3,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '3',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img2,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '4',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img4,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '5',
    title: 'חדר שינה מפנק',
    description: 'חדר שינהה בחיפוי עף עם מיטות רחבות',
    imageUrl: photos.img5,
    room: 'חדר שינה',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '6',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img6,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '7',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img7,
    room: 'חדר לימוד',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '8',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img8,
    room: 'חדר אמבטיה',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '9',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img9,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '10',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img15,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '11',
    title: 'חצר ירוקה',
    description: 'חצר שופעת צמחייה עם נדנדת עץ',
    imageUrl: photos.img13,
    room: 'חצר',
    styles: ['צבעוני', 'כפרי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '12',
    title: 'מטבח צבעוני',
    description: 'מטבח בעיצוב צבעוני ומודרני.',
    imageUrl: photos.img11,
    room: 'מטבח',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '13',
    title: 'סלון מואר',
    description: 'סלון בעיצוב בהיר הפונה לנוף.',
    imageUrl: photos.img19,
    room: 'סלון',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '14',
    title: 'חדר שינה טורקיז',
    description: 'חדר שינה בגווני טורקיז מרגיעים.',
    imageUrl: photos.img18,
    room: 'חדר שינה',
    styles: ['צבעוני', 'מפנק'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '15',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img3,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
];
