import { photos } from './photos';

export interface ImageData {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  room: string;
  styles: string[];
  designer?: string;
  featured: boolean;
}

export const images: ImageData[] = [
  {
    id: '1',
    title: 'מטבח מודרני',
    description: 'מטבח עם קווים נקיים ועיצוב מינימליסטי.',
    imageUrl: photos.img1,
    room: 'מטבח',
    styles: ['מודרני', 'מינימליסטי'],
    designer: 'דנה לוי',
    featured: true,
  },
  {
    id: '2',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img3,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '3',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img2,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '4',
    title: 'סלון מרוהט כהה ',
    description: 'סלון עם ספריית עץ כהה',
    imageUrl: photos.img4,
    room: 'סלון',
    styles: [ 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '5',
    title: 'חדר שינה מפנק',
    description: 'חדר שינהה בחיפוי עף עם מיטות רחבות',
    imageUrl: photos.img5,
    room: 'חדר שינה',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '6',
    title: 'חדר ורוד לילדות',
    description: 'חדר נעים לילדות .',
    imageUrl: photos.img6,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'מאור כץ',
    featured: false,
  },
  {
    id: '7',
    title: 'חדר חלומי לילדה',
    description: 'חדר חלומי לנסיכה',
    imageUrl: photos.img7,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '8',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img8,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '9',
    title: 'חצר יוקרתית',
    description: 'חצר יוקרתית עם בריכה',
    imageUrl: photos.img9,
    room: 'חצר ',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '10',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img15,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '11',
    title: 'חצר ירוקה',
    description: 'חצר שופעת צמחייה עם נדנדת עץ',
    imageUrl: photos.img13,
    room: 'חצר',
    styles: ['צבעוני', 'כפרי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '12',
    title: 'מטבח מודרני',
    description: 'מטבח בעיצוב צבעוני ומודרני.',
    imageUrl: photos.img11,
    room: 'מטבח',
    styles: ['מודרני',],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '13',
    title: 'סלון מואר',
    description: 'סלון בעיצוב בהיר הפונה לנוף.',
    imageUrl: photos.img19,
    room: 'סלון',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '14',
    title: 'חדר שינה טורקיז',
    description: 'חדר שינה בגווני טורקיז מרגיעים.',
    imageUrl: photos.img18,
    room: 'חדר שינה',
    styles: ['צבעוני', 'מפנק'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '15',
    title: 'חדר ילדה צבעוני',
    description: 'חדר ילדה עם אלמנטים צבעוניים.',
    imageUrl: photos.img3,
    room: 'חדר ילדים',
    styles: ['צבעוני', 'נסיכי'],
    designer: 'רוני עוז',
    featured: false,
  },
  {
    id: '16',
    title: 'חדר אמבטייה אפור',
    description: 'חדר אמבטייה בעיצוב מודרני',
    imageUrl: photos.img20,
    room: 'חדר רחצה',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
   {
    id: '17',
    title: 'חדר אמבטייה אפור',
    description: 'חדר אמבטייה בעיצוב מודרני',
    imageUrl: photos.img21,
    room: 'חדר רחצה',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
  //  {
  //   id: '18',
  //   title: 'חדר אמבטייה אפור',
  //   description: 'חדר אמבטייה בעיצוב מודרני',
  //   imageUrl: photos.img22,
  //   room: 'חדר רחצה',
  //   styles: ['מודרני', 'יוקרתי'],
  //   designer: 'רוני עוז',
  //   featured: false,
  // },
   {
    id: '18',
    title: 'סלון יוקרתי בהיר',
    description: 'סלון יוקרתי בעיצוב בהיר עם חלונות גדולים',
    imageUrl: photos.img23,
    room: 'סלון',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
   {
    id: '19',
    title: 'סלון יוקרתי בהיר',
    description: 'סלון יוקרתי בעיצוב בהיר ',
    imageUrl: photos.img24,
    room: 'סלון',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
 {
    id: '20',
    title: 'סלון יוקרתי ',
    description: 'סלון יוקרתי בעיצוב בהיר ',
    imageUrl: photos.img25,
    room: 'סלון',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  }, {
    id: '21',
    title: 'סלון',
    description: 'סלון יוקרתי בעיצוב  ',
    imageUrl: photos.img26,
    room: 'סלון',
    styles: [ 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  }, {
    id: '22',
    title: 'סלון כהה',
    description: 'סלון יוקרתי בעיצוב כהה ',
    imageUrl: photos.img28,
    room: 'סלון',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
   {
    id: '23',
    title: 'סלון כפרי',
    description: 'סלון כפרי אמיתי ',
    imageUrl: photos.img29,
    room: 'סלון',
    styles: [ 'כפרי'],
    designer: 'רוני עוז',
    featured: false,
  },
   {
    id: '24',
    title: 'מטבח ',
    description: 'מטבח בעיצוב  .',
    imageUrl: photos.img30,
    room: 'מטבח',
    styles: ['מודרני',],
    designer: 'רוני עוז',
    featured: false,
  }, {
    id: '25',
    title: 'מטבח מודרני',
    description: 'מטבח בעיצוב צבעוני ומודרני.',
    imageUrl: photos.img31,
    room: 'מטבח',
    styles: ['מודרני',],
    designer: 'רוני עוז',
    featured: false,
  }, {
    id: '26',
    title: 'מטבח פשוט',
    description: 'מטבח בעיצוב צבעוני ומודרני.',
    imageUrl: photos.img32,
    room: 'מטבח',
    styles: ['מודרני',],
    designer: 'רוני עוז',
    featured: false,
  },
   {
    id: '27',
    title: 'חדר שינה מפנק',
    description: 'חדר שינהה בחיפוי עף עם מיטות רחבות',
    imageUrl: photos.img33,
    room: 'חדר שינה',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },
   {
    id: '28',
    title: 'חדר שינה מפנק',
    description: 'חדר שינהה בחיפוי עף עם מיטות רחבות',
    imageUrl: photos.img34,
    room: 'חדר שינה',
    styles: ['מודרני', 'יוקרתי'],
    designer: 'רוני עוז',
    featured: false,
  },

];
